** 3.3 CartPoleの状態を離散化してみる **

# 使用するパッケージの宣言

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import gym

# 定数の設定

In [2]:
ENV = 'CartPole-v0'  # 使用する課題名
NUM_DIZITIZED = 6  # 各状態の離散値への分割数

# CartPoleを実行してみる

In [30]:
env = gym.make(ENV)  # 実行する課題を設定
observation = env.reset()  # 環境の初期化

In [31]:
observation

array([-0.04501884, -0.0399147 , -0.04027506,  0.03450819])

# 離散化の閾値を求める

In [13]:
def bins(clip_min, clip_max, num):
    '''観測した状態（連続値）を離散値にデジタル変換する閾値を求める'''
    return np.linspace(start = clip_min, stop = clip_max, num = num + 1)[1:-1]

In [6]:
np.linspace(-2.4, 2.4, 6 + 1)

array([-2.4, -1.6, -0.8,  0. ,  0.8,  1.6,  2.4])

In [ ]:
np.linspace(-2.4, 2.4, 6 + 1)[1:-1]

# 観測したobservation状態を、離散値に変換する

4つの離散値（NUM_DIZITIZEDが６ならそれぞれ6値）が得られるので、6進数的にコーディングする

In [16]:
def digitize_state(observation):
    '''観測したobservation状態を、離散値に変換する'''
    cart_pos, cart_v, pole_angle, pole_v = observation
    digitized = [
        np.digitize(cart_pos, bins=bins(-2.4, 2.4, NUM_DIZITIZED)),
        np.digitize(cart_v, bins=bins(-3.0, 3.0, NUM_DIZITIZED)),
        np.digitize(pole_angle, bins=bins(-0.5, 0.5, NUM_DIZITIZED)),
        np.digitize(pole_v, bins=bins(-2.0, 2.0, NUM_DIZITIZED))]
    return sum([x * (NUM_DIZITIZED**i) for i, x in enumerate(digitized)])


In [22]:
digitize_state(observation)

561

# sandbox

In [32]:
cart_pos, cart_v, pole_angle, pole_v = observation
digitized = [
    np.digitize(cart_pos, bins=bins(-2.4, 2.4, NUM_DIZITIZED)),
    np.digitize(cart_v, bins=bins(-3.0, 3.0, NUM_DIZITIZED)),
    np.digitize(pole_angle, bins=bins(-0.5, 0.5, NUM_DIZITIZED)),
    np.digitize(pole_v, bins=bins(-2.0, 2.0, NUM_DIZITIZED))]

In [45]:
cart_pos

-0.04501883904139853

In [46]:
bins(-2.4, 2.4, NUM_DIZITIZED)

array([-1.6, -0.8,  0. ,  0.8,  1.6])

In [55]:
np.array([1,1]).shape

(2,)

In [65]:
np.array([4,3,2]).shape

(3,)

In [67]:
type(np.array([4,3,2]))

numpy.ndarray

In [66]:
np.ndarray([4,3,2]).shape

(4, 3, 2)

In [68]:
type(np.ndarray([4,3,2]))

numpy.ndarray

In [44]:
(np.digitize(cart_pos, bins=bins(-2.4, 2.4, NUM_DIZITIZED)))

()

In [12]:
?np.linspace

In [11]:
np.linspace(

array([-2.        ,  0.66666667,  3.33333333,  6.        ])

In [15]:
bins(-2,2,5)

array([-1.2, -0.4,  0.4,  1.2])

In [17]:
observation

array([ 0.00755673,  0.02323561,  0.00788667, -0.03122374])

In [24]:
?np.digitize

In [25]:
np.digitize(3 , 3)

ValueError: object of too small depth for desired array