# Table of Contents
 <p><div class="lev1 toc-item"><a href="#パッケージのimport" data-toc-modified-id="パッケージのimport-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>パッケージのimport</a></div><div class="lev1 toc-item"><a href="#動画の描画関数の宣言" data-toc-modified-id="動画の描画関数の宣言-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>動画の描画関数の宣言</a></div><div class="lev1 toc-item"><a href="#namedtuple" data-toc-modified-id="namedtuple-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>namedtuple</a></div><div class="lev1 toc-item"><a href="#定数の設定" data-toc-modified-id="定数の設定-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>定数の設定</a></div><div class="lev1 toc-item"><a href="#経験を保存するメモリクラスを定義します" data-toc-modified-id="経験を保存するメモリクラスを定義します-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>経験を保存するメモリクラスを定義します</a></div><div class="lev2 toc-item"><a href="#sandbox" data-toc-modified-id="sandbox-51"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>sandbox</a></div><div class="lev1 toc-item"><a href="#Brain" data-toc-modified-id="Brain-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Brain</a></div><div class="lev2 toc-item"><a href="#brain-解説" data-toc-modified-id="brain-解説-61"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>brain 解説</a></div><div class="lev3 toc-item"><a href="#initialization" data-toc-modified-id="initialization-611"><span class="toc-item-num">6.1.1&nbsp;&nbsp;</span>initialization</a></div><div class="lev3 toc-item"><a href="#replay" data-toc-modified-id="replay-612"><span class="toc-item-num">6.1.2&nbsp;&nbsp;</span>replay</a></div><div class="lev4 toc-item"><a href="#メモリサイズの確認" data-toc-modified-id="メモリサイズの確認-6121"><span class="toc-item-num">6.1.2.1&nbsp;&nbsp;</span>メモリサイズの確認</a></div><div class="lev4 toc-item"><a href="#ミニバッチの作成" data-toc-modified-id="ミニバッチの作成-6122"><span class="toc-item-num">6.1.2.2&nbsp;&nbsp;</span>ミニバッチの作成</a></div><div class="lev4 toc-item"><a href="#教師信号となるQ(s_t,-a_t)値を求める" data-toc-modified-id="教師信号となるQ(s_t,-a_t)値を求める-6123"><span class="toc-item-num">6.1.2.3&nbsp;&nbsp;</span>教師信号となるQ(s_t, a_t)値を求める</a></div><div class="lev3 toc-item"><a href="#decide_action" data-toc-modified-id="decide_action-613"><span class="toc-item-num">6.1.3&nbsp;&nbsp;</span>decide_action</a></div><div class="lev2 toc-item"><a href="#解説終わり" data-toc-modified-id="解説終わり-62"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>解説終わり</a></div><div class="lev1 toc-item"><a href="#Agent" data-toc-modified-id="Agent-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Agent</a></div><div class="lev1 toc-item"><a href="#CartPoleを実行する環境のクラスです" data-toc-modified-id="CartPoleを実行する環境のクラスです-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>CartPoleを実行する環境のクラスです</a></div><div class="lev1 toc-item"><a href="#classでなくしてみる" data-toc-modified-id="classでなくしてみる-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>classでなくしてみる</a></div><div class="lev2 toc-item"><a href="#envのinit" data-toc-modified-id="envのinit-91"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>envのinit</a></div><div class="lev3 toc-item"><a href="#Agent作成" data-toc-modified-id="Agent作成-911"><span class="toc-item-num">9.1.1&nbsp;&nbsp;</span>Agent作成</a></div><div class="lev2 toc-item"><a href="#envのfor-loop" data-toc-modified-id="envのfor-loop-92"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>envのfor loop</a></div><div class="lev3 toc-item"><a href="#agent.get_actionはepsilon-greedy法により決定されたaction(この例の場合、右か左かのゼロイチ）を返す" data-toc-modified-id="agent.get_actionはepsilon-greedy法により決定されたaction(この例の場合、右か左かのゼロイチ）を返す-921"><span class="toc-item-num">9.2.1&nbsp;&nbsp;</span>agent.get_actionは$\epsilon$-greedy法により決定されたaction(この例の場合、右か左かのゼロイチ）を返す</a></div><div class="lev3 toc-item"><a href="#actionを与えるとenvがどうなるかを計算してくれる：" data-toc-modified-id="actionを与えるとenvがどうなるかを計算してくれる：-922"><span class="toc-item-num">9.2.2&nbsp;&nbsp;</span>actionを与えるとenvがどうなるかを計算してくれる：</a></div><div class="lev3 toc-item"><a href="#終了していたら" data-toc-modified-id="終了していたら-923"><span class="toc-item-num">9.2.3&nbsp;&nbsp;</span>終了していたら</a></div><div class="lev3 toc-item"><a href="#エージェントが（状態、アクション、次のアクション、報酬）を記憶" data-toc-modified-id="エージェントが（状態、アクション、次のアクション、報酬）を記憶-924"><span class="toc-item-num">9.2.4&nbsp;&nbsp;</span>エージェントが（状態、アクション、次のアクション、報酬）を記憶</a></div><div class="lev3 toc-item"><a href="#Experience-ReplayでQ関数を更新する" data-toc-modified-id="Experience-ReplayでQ関数を更新する-925"><span class="toc-item-num">9.2.5&nbsp;&nbsp;</span>Experience ReplayでQ関数を更新する</a></div><div class="lev2 toc-item"><a href="#brain" data-toc-modified-id="brain-93"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>brain</a></div><div class="lev3 toc-item"><a href="#サンプルがたまった学習済みのbrainを拝借" data-toc-modified-id="サンプルがたまった学習済みのbrainを拝借-931"><span class="toc-item-num">9.3.1&nbsp;&nbsp;</span>サンプルがたまった学習済みのbrainを拝借</a></div><div class="lev3 toc-item"><a href="#mini-batch取得" data-toc-modified-id="mini-batch取得-932"><span class="toc-item-num">9.3.2&nbsp;&nbsp;</span>mini batch取得</a></div><div class="lev3 toc-item"><a href="#mini-batchをtorchが食える形式に変形" data-toc-modified-id="mini-batchをtorchが食える形式に変形-933"><span class="toc-item-num">9.3.3&nbsp;&nbsp;</span>mini batchをtorchが食える形式に変形</a></div><div class="lev3 toc-item"><a href="#推論モードへ切り替え" data-toc-modified-id="推論モードへ切り替え-934"><span class="toc-item-num">9.3.4&nbsp;&nbsp;</span>推論モードへ切り替え</a></div><div class="lev3 toc-item"><a href="#ネットワークが出力したQ(s_t,-a_t)を求める" data-toc-modified-id="ネットワークが出力したQ(s_t,-a_t)を求める-935"><span class="toc-item-num">9.3.5&nbsp;&nbsp;</span>ネットワークが出力したQ(s_t, a_t)を求める</a></div><div class="lev3 toc-item"><a href="#cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成" data-toc-modified-id="cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成-936"><span class="toc-item-num">9.3.6&nbsp;&nbsp;</span>cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成</a></div><div class="lev4 toc-item"><a href="#doneでないnext-state:" data-toc-modified-id="doneでないnext-state:-9361"><span class="toc-item-num">9.3.6.1&nbsp;&nbsp;</span>doneでないnext state:</a></div><div class="lev4 toc-item"><a href="#next-statenにおける行動価値関数" data-toc-modified-id="next-statenにおける行動価値関数-9362"><span class="toc-item-num">9.3.6.2&nbsp;&nbsp;</span>next statenにおける行動価値関数</a></div><div class="lev4 toc-item"><a href="#next-stateにおける行動価値関数の最大値" data-toc-modified-id="next-stateにおける行動価値関数の最大値-9363"><span class="toc-item-num">9.3.6.3&nbsp;&nbsp;</span>next stateにおける行動価値関数の最大値</a></div><div class="lev1 toc-item"><a href="#sandbox" data-toc-modified-id="sandbox-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>sandbox</a></div><div class="lev3 toc-item"><a href="#経験を記憶するメモリオブジェクトを生成" data-toc-modified-id="経験を記憶するメモリオブジェクトを生成-1001"><span class="toc-item-num">10.0.1&nbsp;&nbsp;</span>経験を記憶するメモリオブジェクトを生成</a></div><div class="lev3 toc-item"><a href="#ニューラルネットワークを構築" data-toc-modified-id="ニューラルネットワークを構築-1002"><span class="toc-item-num">10.0.2&nbsp;&nbsp;</span>ニューラルネットワークを構築</a></div><div class="lev3 toc-item"><a href="#最適化手法の設定" data-toc-modified-id="最適化手法の設定-1003"><span class="toc-item-num">10.0.3&nbsp;&nbsp;</span>最適化手法の設定</a></div><div class="lev3 toc-item"><a href="#replay" data-toc-modified-id="replay-1004"><span class="toc-item-num">10.0.4&nbsp;&nbsp;</span>replay</a></div>


** 5.3、5.4  PyTorchでDQN **

# パッケージのimport

In [6]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import gym

# 動画の描画関数の宣言
参考URL http://nbviewer.jupyter.org/github/patrickmineault/xcorr-notebooks/blob/master/Render%20OpenAI%20gym%20as%20GIF.ipynb

In [7]:
from JSAnimation.IPython_display import display_animation
from matplotlib import animation
from IPython.display import display


def display_frames_as_gif(frames):
    """
    Displays a list of frames as a gif, with controls
    """
    plt.figure(figsize=(frames[0].shape[1]/72.0, frames[0].shape[0]/72.0),
               dpi=72)
    patch = plt.imshow(frames[0])
    plt.axis('off')

    def animate(i):
        patch.set_data(frames[i])

    anim = animation.FuncAnimation(plt.gcf(), animate, frames=len(frames),
                                   interval=50)

    anim.save('movie_cartpole_DQN.mp4')  # 動画のファイル名と保存です
    display(display_animation(anim, default_mode='loop'))
    

# namedtuple

本コードでは、namedtupleを使用します。

namedtupleを使うことで、値をフィールド名とペアで格納できます。

すると値に対して、フィールド名でアクセスできて便利です。

https://docs.python.jp/3/library/collections.html#collections.namedtuple

以下は使用例です

In [8]:
from collections import namedtuple

Tr = namedtuple('tr', ('name_a', 'value_b'))
Tr_object = Tr('名前Aです', 100)

print(Tr_object)  # 出力：tr(name_a='名前Aです', value_b=100)
print(Tr_object.value_b)  # 出力：100

tr(name_a='名前Aです', value_b=100)
100


In [9]:
Tr_object.name_a

'名前Aです'

In [10]:
# namedtupleを生成
from collections import namedtuple

Transition = namedtuple(
    'Transition', ('state', 'action', 'next_state', 'reward'))


# 定数の設定

In [11]:
ENV = 'CartPole-v0'  # 使用する課題名
GAMMA = 0.99  # 時間割引率
MAX_STEPS = 200  # 1試行のstep数
NUM_EPISODES = 500  # 最大試行回数

# 経験を保存するメモリクラスを定義します

In [12]:
class ReplayMemory:

    def __init__(self, CAPACITY):
        self.capacity = CAPACITY  # メモリの最大長さ
        self.memory = []  # 経験を保存する変数
        self.index = 0  # 保存するindexを示す変数

    def push(self, state, action, state_next, reward):
        '''transition = (state, action, state_next, reward)をメモリに保存する'''

        if len(self.memory) < self.capacity:
            self.memory.append(None)  # メモリが満タンでないときは足す

        # namedtupleのTransitionを使用し、値とフィールド名をペアにして保存します
        self.memory[self.index] = Transition(state, action, state_next, reward)

        self.index = (self.index + 1) % self.capacity  # 保存するindexを1つずらす

    def sample(self, batch_size):
        '''batch_size分だけ、ランダムに保存内容を取り出す'''
        return random.sample(self.memory, batch_size)

    def __len__(self):
        '''関数lenに対して、現在の変数memoryの長さを返す'''
        return len(self.memory)

In [8]:
import random

## sandbox

In [9]:
tmp = ReplayMemory(3)

In [10]:
tmp.push(1,2,3,4)

In [11]:
tmp.push(2,4,3,1)

In [18]:
tmp.sample(2)

[Transition(state=1, action=2, next_state=3, reward=4),
 Transition(state=2, action=4, next_state=3, reward=1)]

# Brain

エージェントが持つ脳となるクラスです、DQNを実行します

methodは

* replay: Experience Replayでネットワークの結合パラメータを学習
* decide_action: アクション決定

Q関数をディープラーニングのネットワークをクラスとして定義

In [13]:
import random
import torch
from torch import nn
from torch import optim
import torch.nn.functional as F

BATCH_SIZE = 32
CAPACITY = 10000

In [14]:
class Brain:
    def __init__(self, num_states, num_actions):
        self.num_actions = num_actions  # CartPoleの行動（右に左に押す）の2を取得

        # 経験を記憶するメモリオブジェクトを生成
        self.memory = ReplayMemory(CAPACITY)

        # ニューラルネットワークを構築
        self.model = nn.Sequential()
        self.model.add_module('fc1', nn.Linear(num_states, 32))
        self.model.add_module('relu1', nn.ReLU())
        self.model.add_module('fc2', nn.Linear(32, 32))
        self.model.add_module('relu2', nn.ReLU())
        self.model.add_module('fc3', nn.Linear(32, num_actions))

        print(self.model)  # ネットワークの形を出力

        # 最適化手法の設定
        self.optimizer = optim.Adam(self.model.parameters(), lr=0.0001)

    def replay(self):
        '''Experience Replayでネットワークの結合パラメータを学習'''

        # -----------------------------------------
        # 1. メモリサイズの確認
        # -----------------------------------------
        # 1.1 メモリサイズがミニバッチより小さい間は何もしない
        if len(self.memory) < BATCH_SIZE:
            return

        # -----------------------------------------
        # 2. ミニバッチの作成
        # -----------------------------------------
        # 2.1 メモリからミニバッチ分のデータを取り出す
        transitions = self.memory.sample(BATCH_SIZE)

        # 2.2 各変数をミニバッチに対応する形に変形
        # transitionsは1stepごとの(state, action, state_next, reward)が、BATCH_SIZE分格納されている
        # つまり、(state, action, state_next, reward)×BATCH_SIZE
        # これをミニバッチにしたい。つまり
        # (state×BATCH_SIZE, action×BATCH_SIZE, state_next×BATCH_SIZE, reward×BATCH_SIZE)にする
        batch = Transition(*zip(*transitions))

        # 2.3 各変数の要素をミニバッチに対応する形に変形し、ネットワークで扱えるようVariableにする
        # 例えばstateの場合、[torch.FloatTensor of size 1x4]がBATCH_SIZE分並んでいるのですが、
        # それを torch.FloatTensor of size BATCH_SIZEx4 に変換します
        # 状態、行動、報酬、non_finalの状態のミニバッチのVariableを作成
        # catはConcatenates（結合）のことです。
        state_batch = torch.cat(batch.state)
        action_batch = torch.cat(batch.action)
        reward_batch = torch.cat(batch.reward)
        non_final_next_states = torch.cat([s for s in batch.next_state
                                           if s is not None])

        # -----------------------------------------
        # 3. 教師信号となるQ(s_t, a_t)値を求める
        # -----------------------------------------
        # 3.1 ネットワークを推論モードに切り替える
        self.model.eval()

        # 3.2 ネットワークが出力したQ(s_t, a_t)を求める
        # self.model(state_batch)は、右左の両方のQ値を出力しており
        # [torch.FloatTensor of size BATCH_SIZEx2]になっている。
        # ここから実行したアクションa_tに対応するQ値を求めるため、action_batchで行った行動a_tが右か左かのindexを求め
        # それに対応するQ値をgatherでひっぱり出す。
        state_action_values = self.model(state_batch).gather(1, action_batch)

        # 3.3 max{Q(s_t+1, a)}値を求める。ただし次の状態があるかに注意。

        # cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成
        non_final_mask = torch.ByteTensor(tuple(map(lambda s: s is not None,
                                                    batch.next_state)))
        # まずは全部0にしておく
        next_state_values = torch.zeros(BATCH_SIZE)

        # 次の状態があるindexの最大Q値を求める
        # 出力にアクセスし、max(1)で列方向の最大値の[値、index]を求めます
        # そしてそのQ値（index=0）を出力します
        # detachでその値を取り出します
        next_state_values[non_final_mask] = self.model(
            non_final_next_states).max(1)[0].detach()

        # 3.4 教師となるQ(s_t, a_t)値を、Q学習の式から求める
        expected_state_action_values = reward_batch + GAMMA * next_state_values

        # -----------------------------------------
        # 4. 結合パラメータの更新
        # -----------------------------------------
        # 4.1 ネットワークを訓練モードに切り替える
        self.model.train()

        # 4.2 損失関数を計算する（smooth_l1_lossはHuberloss）
        # expected_state_action_valuesは
        # sizeが[minbatch]になっているので、unsqueezeで[minibatch x 1]へ
        loss = F.smooth_l1_loss(state_action_values,
                                expected_state_action_values.unsqueeze(1))

        # 4.3 結合パラメータを更新する
        self.optimizer.zero_grad()  # 勾配をリセット
        loss.backward()  # バックプロパゲーションを計算
        self.optimizer.step()  # 結合パラメータを更新

    def decide_action(self, state, episode):
        '''現在の状態に応じて、行動を決定する'''
        # ε-greedy法で徐々に最適行動のみを採用する
        epsilon = 0.5 * (1 / (episode + 1))

        if epsilon <= np.random.uniform(0, 1):
            self.model.eval()  # ネットワークを推論モードに切り替える
            with torch.no_grad():
                action = self.model(state).max(1)[1].view(1, 1)
            # ネットワークの出力の最大値のindexを取り出します = max(1)[1]
            # .view(1,1)は[torch.LongTensor of size 1]　を size 1x1 に変換します

        else:
            # 0,1の行動をランダムに返す
            action = torch.LongTensor(
                [[random.randrange(self.num_actions)]])  # 0,1の行動をランダムに返す
            # actionは[torch.LongTensor of size 1x1]の形になります

        return action

## brain 解説

### initialization

```python
class Brain:
    def __init__(self, num_states, num_actions):
        self.num_actions = num_actions  # CartPoleの行動（右に左に押す）の2を取得

        # 経験を記憶するメモリオブジェクトを生成
        self.memory = ReplayMemory(CAPACITY)

        # ニューラルネットワークを構築
        self.model = nn.Sequential()
        self.model.add_module('fc1', nn.Linear(num_states, 32))
        self.model.add_module('relu1', nn.ReLU())
        self.model.add_module('fc2', nn.Linear(32, 32))
        self.model.add_module('relu2', nn.ReLU())
        self.model.add_module('fc3', nn.Linear(32, num_actions))

        print(self.model)  # ネットワークの形を出力

        # 最適化手法の設定
        self.optimizer = optim.Adam(self.model.parameters(), lr=0.0001)
```

### replay

Experience Replayでネットワークの結合パラメータを学習

```python
    def replay(self):
```

#### メモリサイズの確認
メモリサイズがミニバッチより小さい間は何もしない

In [20]:
%%bash
git commit -a -m "since quite a long time ago"

[master 170680a] since quite a long time ago
 1 file changed, 91 insertions(+), 29 deletions(-)


```python
        if len(self.memory) < BATCH_SIZE:
            return
```

#### ミニバッチの作成
##### メモリからミニバッチ分のデータを取り出す

        transitions = self.memory.sample(BATCH_SIZE)

##### 各変数をミニバッチに対応する形に変形
* transitionsは1stepごとの
$$\text{(state, action, state_next, reward)}$$  
  が、BATCH_SIZE分格納されている
  
* つまり、
  $$\text{(state, action, state_next, reward)}\times\text{BATCH_SIZE}$$
  
* これをミニバッチにしたい。つまり
    $$(\text{state}\times\text{BATCH_SIZE}, ~\text{action}\times\text{BATCH_SIZE}, ~\text{state_next}\times\text{BATCH_SIZE},~ \text{reward}\times\text{BATCH_SIZE})$$
  にする

        batch = Transition(*zip(*transitions))

##### 各変数の要素をミニバッチに対応する形に変形し、ネットワークで扱えるようVariableにする
*  例えばstateの場合、[torch.FloatTensor of size 1x4]がBATCH_SIZE分並んでいる
* それを torch.FloatTensor of size BATCH_SIZEx4 に変換します
```python 
        # 状態、行動、報酬、non_finalの状態のミニバッチのVariableを作成
        # catはConcatenates（結合）のことです。
        state_batch = torch.cat(batch.state)
        action_batch = torch.cat(batch.action)
        reward_batch = torch.cat(batch.reward)
        non_final_next_states = torch.cat([s for s in batch.next_state
                                           if s is not None])
```

#### 教師信号となるQ(s_t, a_t)値を求める
##### ネットワークを推論モードに切り替える
        self.model.eval()

##### ネットワークが出力したQ(s_t, a_t)を求める
* self.model(state_batch)は、右左の両方のQ値を出力しており[torch.FloatTensor of size BATCH_SIZEx2]になっている。
* ここから実行したアクションa_tに対応するQ値を求めるため、action_batchで行った行動a_tが右か左かのindexを求め、それに対応するQ値をgatherでひっぱり出す。
        
```python
        state_action_values = self.model(state_batch).gather(1, action_batch)
```

        state_action_values = self.model(state_batch).gather(1, action_batch)

        # 3.3 max{Q(s_t+1, a)}値を求める。ただし次の状態があるかに注意。

        # cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成
        non_final_mask = torch.ByteTensor(tuple(map(lambda s: s is not None,
                                                    batch.next_state)))
        # まずは全部0にしておく
        next_state_values = torch.zeros(BATCH_SIZE)

        # 次の状態があるindexの最大Q値を求める
        # 出力にアクセスし、max(1)で列方向の最大値の[値、index]を求めます
        # そしてそのQ値（index=0）を出力します
        # detachでその値を取り出します
        next_state_values[non_final_mask] = self.model(
            non_final_next_states).max(1)[0].detach()

        # 3.4 教師となるQ(s_t, a_t)値を、Q学習の式から求める
        expected_state_action_values = reward_batch + GAMMA * next_state_values

        # -----------------------------------------
        # 4. 結合パラメータの更新
        # -----------------------------------------
        # 4.1 ネットワークを訓練モードに切り替える
        self.model.train()

        # 4.2 損失関数を計算する（smooth_l1_lossはHuberloss）
        # expected_state_action_valuesは
        # sizeが[minbatch]になっているので、unsqueezeで[minibatch x 1]へ
        loss = F.smooth_l1_loss(state_action_values,
                                expected_state_action_values.unsqueeze(1))

        # 4.3 結合パラメータを更新する
        self.optimizer.zero_grad()  # 勾配をリセット
        loss.backward()  # バックプロパゲーションを計算
        self.optimizer.step()  # 結合パラメータを更新

### decide_action

    def decide_action(self, state, episode):
        '''現在の状態に応じて、行動を決定する'''
        # ε-greedy法で徐々に最適行動のみを採用する
        epsilon = 0.5 * (1 / (episode + 1))

        if epsilon <= np.random.uniform(0, 1):
            self.model.eval()  # ネットワークを推論モードに切り替える
            with torch.no_grad():
                action = self.model(state).max(1)[1].view(1, 1)
            # ネットワークの出力の最大値のindexを取り出します = max(1)[1]
            # .view(1,1)は[torch.LongTensor of size 1]　を size 1x1 に変換します

        else:
            # 0,1の行動をランダムに返す
            action = torch.LongTensor(
                [[random.randrange(self.num_actions)]])  # 0,1の行動をランダムに返す
            # actionは[torch.LongTensor of size 1x1]の形になります

        return action
```

## 解説終わり

In [ ]:
class Brain:
    def __init__(self, num_states, num_actions):
        self.num_actions = num_actions  # CartPoleの行動（右に左に押す）の2を取得


        print(self.model)  # ネットワークの形を出力

        # 
       

    def replay(self):
        '''Experience Replayでネットワークの結合パラメータを学習'''

        # -----------------------------------------
        # 1. メモリサイズの確認
        # -----------------------------------------
        # 1.1 メモリサイズがミニバッチより小さい間は何もしない
        if len(self.memory) < BATCH_SIZE:
            return

        # -----------------------------------------
        # 2. ミニバッチの作成
        # -----------------------------------------
        # 2.1 メモリからミニバッチ分のデータを取り出す
        transitions = self.memory.sample(BATCH_SIZE)

        # 2.2 各変数をミニバッチに対応する形に変形
        # transitionsは1stepごとの(state, action, state_next, reward)が、BATCH_SIZE分格納されている
        # つまり、(state, action, state_next, reward)×BATCH_SIZE
        # これをミニバッチにしたい。つまり
        # (state×BATCH_SIZE, action×BATCH_SIZE, state_next×BATCH_SIZE, reward×BATCH_SIZE)にする
        batch = Transition(*zip(*transitions))

        # 2.3 各変数の要素をミニバッチに対応する形に変形し、ネットワークで扱えるようVariableにする
        # 例えばstateの場合、[torch.FloatTensor of size 1x4]がBATCH_SIZE分並んでいるのですが、
        # それを torch.FloatTensor of size BATCH_SIZEx4 に変換します
        # 状態、行動、報酬、non_finalの状態のミニバッチのVariableを作成
        # catはConcatenates（結合）のことです。
        state_batch = torch.cat(batch.state)
        action_batch = torch.cat(batch.action)
        reward_batch = torch.cat(batch.reward)
        non_final_next_states = torch.cat([s for s in batch.next_state
                                           if s is not None])

        # -----------------------------------------
        # 3. 教師信号となるQ(s_t, a_t)値を求める
        # -----------------------------------------
        # 3.1 ネットワークを推論モードに切り替える
        self.model.eval()

        # 3.2 ネットワークが出力したQ(s_t, a_t)を求める
        # self.model(state_batch)は、右左の両方のQ値を出力しており
        # [torch.FloatTensor of size BATCH_SIZEx2]になっている。
        # ここから実行したアクションa_tに対応するQ値を求めるため、action_batchで行った行動a_tが右か左かのindexを求め
        # それに対応するQ値をgatherでひっぱり出す。
        state_action_values = self.model(state_batch).gather(1, action_batch)

        # 3.3 max{Q(s_t+1, a)}値を求める。ただし次の状態があるかに注意。

        # cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成
        non_final_mask = torch.ByteTensor(tuple(map(lambda s: s is not None,
                                                    batch.next_state)))
        # まずは全部0にしておく
        next_state_values = torch.zeros(BATCH_SIZE)

        # 次の状態があるindexの最大Q値を求める
        # 出力にアクセスし、max(1)で列方向の最大値の[値、index]を求めます
        # そしてそのQ値（index=0）を出力します
        # detachでその値を取り出します
        next_state_values[non_final_mask] = self.model(
            non_final_next_states).max(1)[0].detach()

        # 3.4 教師となるQ(s_t, a_t)値を、Q学習の式から求める
        expected_state_action_values = reward_batch + GAMMA * next_state_values

        # -----------------------------------------
        # 4. 結合パラメータの更新
        # -----------------------------------------
        # 4.1 ネットワークを訓練モードに切り替える
        self.model.train()

        # 4.2 損失関数を計算する（smooth_l1_lossはHuberloss）
        # expected_state_action_valuesは
        # sizeが[minbatch]になっているので、unsqueezeで[minibatch x 1]へ
        loss = F.smooth_l1_loss(state_action_values,
                                expected_state_action_values.unsqueeze(1))

        # 4.3 結合パラメータを更新する
        self.optimizer.zero_grad()  # 勾配をリセット
        loss.backward()  # バックプロパゲーションを計算
        self.optimizer.step()  # 結合パラメータを更新

    def decide_action(self, state, episode):
        '''現在の状態に応じて、行動を決定する'''
        # ε-greedy法で徐々に最適行動のみを採用する
        epsilon = 0.5 * (1 / (episode + 1))

        if epsilon <= np.random.uniform(0, 1):
            self.model.eval()  # ネットワークを推論モードに切り替える
            with torch.no_grad():
                action = self.model(state).max(1)[1].view(1, 1)
            # ネットワークの出力の最大値のindexを取り出します = max(1)[1]
            # .view(1,1)は[torch.LongTensor of size 1]　を size 1x1 に変換します

        else:
            # 0,1の行動をランダムに返す
            action = torch.LongTensor(
                [[random.randrange(self.num_actions)]])  # 0,1の行動をランダムに返す
            # actionは[torch.LongTensor of size 1x1]の形になります

        return action

In [ ]:
class myBrain0:
    def __init__(self, num_states, num_actions):
        self.num_actions = num_actions  # CartPoleの行動（右に左に押す）の2を取得

        # 経験を記憶するメモリオブジェクトを生成
        self.memory = ReplayMemory(CAPACITY)

        # ニューラルネットワークを構築
        self.model = nn.Sequential()
        self.model.add_module('fc1', nn.Linear(num_states, 32))
        self.model.add_module('relu1', nn.ReLU())
        self.model.add_module('fc2', nn.Linear(32, 32))
        self.model.add_module('relu2', nn.ReLU())
        self.model.add_module('fc3', nn.Linear(32, num_actions))

        print(self.model)  # ネットワークの形を出力

        # 最適化手法の設定
        self.optimizer = optim.Adam(self.model.parameters(), lr=0.0001)

* メモリサイズの確認
    * メモリサイズがミニバッチより小さい間は何もしない
* ミニバッチの作成
    * メモリからミニバッチ分のデータを取り出す
    

    
```python
        batch = Transition(*zip(*transitions))
```

In [ ]:
1+2 

$1+2$

* 各変数をミニバッチに対応する形に変形
    * transitionsは1stepごとの(state, action, state_next, reward)が、BATCH_SIZE分格納されている
    * つまり$\(state, action, state_next, reward)\times\text{BATCH_SIZE}$    

    * これをミニバッチにしたい。つまり
    $$(\text{state}\times\text{BATCH_SIZE}, \\text{action}\times\text{BATCH_SIZE}, \text{state_next}\times\text{BATCH_SIZE},\text{reward}\times\text{BATCH_SIZE})$$
    にする
   

 * 各変数の要素をミニバッチに対応する形に変形し、ネットワークで扱えるようVariableにする

        例えばstateの場合、[torch.FloatTensor of size 1x4]がBATCH_SIZE分並んでいるのですが、
        それを torch.FloatTensor of size BATCH_SIZEx4 に変換します
        状態、行動、報酬、non_finalの状態のミニバッチのVariableを作成
        catはConcatenates（結合）のことです。

In [ ]:
class myBrain1(myBrain0):
    def replay(self):
        '''Experience Replayでネットワークの結合パラメータを学習'''

        # -----------------------------------------
        # 1. メモリサイズの確認
        # -----------------------------------------
        # 1.1 メモリサイズがミニバッチより小さい間は何もしない
        if len(self.memory) < BATCH_SIZE:
            return

        # -----------------------------------------
        # 2. ミニバッチの作成
        # -----------------------------------------
        # 2.1 メモリからミニバッチ分のデータを取り出す
        transitions = self.memory.sample(BATCH_SIZE)

        # 2.2 各変数をミニバッチに対応する形に変形

        batch = Transition(*zip(*transitions))

        # 2.3 各変数の要素をミニバッチに対応する形に変形し、ネットワークで扱えるようVariableにする
        state_batch = torch.cat(batch.state)
        action_batch = torch.cat(batch.action)
        reward_batch = torch.cat(batch.reward)
        non_final_next_states = torch.cat([s for s in batch.next_state
                                           if s is not None])

        # -----------------------------------------
        # 3. 教師信号となるQ(s_t, a_t)値を求める
        # -----------------------------------------
        # 3.1 ネットワークを推論モードに切り替える
        self.model.eval()

        # 3.2 ネットワークが出力したQ(s_t, a_t)を求める

        state_action_values = self.model(state_batch).gather(1, action_batch)

        # 3.3 max{Q(s_t+1, a)}値を求める。ただし次の状態があるかに注意。

        # cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成
        non_final_mask = torch.ByteTensor(tuple(map(lambda s: s is not None,
                                                    batch.next_state)))
        # まずは全部0にしておく
        next_state_values = torch.zeros(BATCH_SIZE)

        # 次の状態があるindexの最大Q値を求める
        # 出力にアクセスし、max(1)で列方向の最大値の[値、index]を求めます
        # そしてそのQ値（index=0）を出力します
        # detachでその値を取り出します
        next_state_values[non_final_mask] = self.model(
            non_final_next_states).max(1)[0].detach()

        # 3.4 教師となるQ(s_t, a_t)値を、Q学習の式から求める
        expected_state_action_values = reward_batch + GAMMA * next_state_values

        # -----------------------------------------
        # 4. 結合パラメータの更新
        # -----------------------------------------
        # 4.1 ネットワークを訓練モードに切り替える
        self.model.train()

        # 4.2 損失関数を計算する（smooth_l1_lossはHuberloss）
        # expected_state_action_valuesは
        # sizeが[minbatch]になっているので、unsqueezeで[minibatch x 1]へ
        loss = F.smooth_l1_loss(state_action_values,
                                expected_state_action_values.unsqueeze(1))

        # 4.3 結合パラメータを更新する
        self.optimizer.zero_grad()  # 勾配をリセット
        loss.backward()  # バックプロパゲーションを計算
        self.optimizer.step()  # 結合パラメータを更新

In [ ]:
class myBrain2(myBrain1):
    def decide_action(self, state, episode):
        '''現在の状態に応じて、行動を決定する'''
        # 
        -greedy法で徐々に最適行動のみを採用する
        epsilon = 0.5 * (1 / (episode + 1))

        if epsilon <= np.random.uniform(0, 1):
            self.model.eval()  # ネットワークを推論モードに切り替える
            with torch.no_grad():
                action = self.model(state).max(1)[1].view(1, 1)
            # ネットワークの出力の最大値のindexを取り出します = max(1)[1]
            # .view(1,1)は[torch.LongTensor of size 1]　を size 1x1 に変換します

        else:
            # 0,1の行動をランダムに返す
            action = torch.LongTensor(
                [[random.randrange(self.num_actions)]])  # 0,1の行動をランダムに返す
            # actionは[torch.LongTensor of size 1x1]の形になります

        return action

# Agent
CartPoleで動くエージェントクラスです、棒付き台車そのものになります

methodは


* 行動価値Qを更新
*  状態を与えると行動を決定
*  状態、選択するアクション、次の状態、報酬などを記憶

In [30]:
class Agent:
    def __init__(self, num_states, num_actions):
        '''課題の状態と行動の数を設定する'''
        self.brain = Brain(num_states, num_actions)  # エージェントが行動を決定するための頭脳を生成

    def update_q_function(self):
        '''Q関数を更新する'''
        self.brain.replay()

    def get_action(self, state, episode):
        '''行動を決定する'''
        action = self.brain.decide_action(state, episode)
        return action

    def memorize(self, state, action, state_next, reward):
        '''memoryオブジェクトに、state, action, state_next, rewardの内容を保存する'''
        self.brain.memory.push(state, action, state_next, reward)

# CartPoleを実行する環境のクラスです

In [79]:
class Environment:

    def __init__(self):
        self.env = gym.make(ENV)  # 実行する課題を設定
        num_states = self.env.observation_space.shape[0]  # 課題の状態数4を取得
        num_actions = self.env.action_space.n  # CartPoleの行動（右に左に押す）の2を取得
        self.agent = Agent(num_states, num_actions)  # 環境内で行動するAgentを生成

        
    def run(self):
        '''実行'''
        episode_10_list = np.zeros(10)  # 10試行分の立ち続けたstep数を格納し、平均ステップ数を出力に利用
        complete_episodes = 0  # 195step以上連続で立ち続けた試行数
        episode_final = False  # 最後の試行フラグ
        frames = []  # 最後の試行を動画にするために画像を格納する変数

        for episode in range(NUM_EPISODES):  # 最大試行数分繰り返す
            observation = self.env.reset()  # 環境の初期化

            state = observation  # 観測をそのまま状態sとして使用
            state = torch.from_numpy(state).type(
                torch.FloatTensor)  # NumPy変数をPyTorchのテンソルに変換
            state = torch.unsqueeze(state, 0)  # size 4をsize 1x4に変換

            for step in range(MAX_STEPS):  # 1エピソードのループ

                if episode_final is True:  # 最終試行ではframesに各時刻の画像を追加していく
                    frames.append(self.env.render(mode='rgb_array'))

                action = self.agent.get_action(state, episode)  # 行動を求める

                # 行動a_tの実行により、s_{t+1}とdoneフラグを求める
                # actionから.item()を指定して、中身を取り出す
                observation_next, _, done, _ = self.env.step(
                    action.item())  # rewardとinfoは使わないので_にする

                # 報酬を与える。さらにepisodeの終了評価と、state_nextを設定する
                if done:  # ステップ数が200経過するか、一定角度以上傾くとdoneはtrueになる
                    state_next = None  # 次の状態はないので、Noneを格納

                    # 直近10episodeの立てたstep数リストに追加
                    episode_10_list = np.hstack(
                        (episode_10_list[1:], step + 1))

                    if step < 195:
                        reward = torch.FloatTensor(
                            [-1.0])  # 途中でこけたら罰則として報酬-1を与える
                        complete_episodes = 0  # 連続成功記録をリセット
                    else:
                        reward = torch.FloatTensor([1.0])  # 立ったまま終了時は報酬1を与える
                        complete_episodes = complete_episodes + 1  # 連続記録を更新
                else:
                    reward = torch.FloatTensor([0.0])  # 普段は報酬0
                    state_next = observation_next  # 観測をそのまま状態とする
                    state_next = torch.from_numpy(state_next).type(
                        torch.FloatTensor)  # numpy変数をPyTorchのテンソルに変換
                    state_next = torch.unsqueeze(state_next, 0)  # size 4をsize 1x4に変換

                # メモリに経験を追加
                self.agent.memorize(state, action, state_next, reward)

                # Experience ReplayでQ関数を更新する
                self.agent.update_q_function()

                # 観測の更新
                state = state_next

                # 終了時の処理
                if done:
                    print('%d Episode: Finished after %d steps：10試行の平均step数 = %.1lf' % (
                        episode, step + 1, episode_10_list.mean()))
                    break

            if episode_final is True:
                # 動画を保存と描画
                display_frames_as_gif(frames)
                break

            # 10連続で200step経ち続けたら成功
            if complete_episodes >= 10:
                print('10回連続成功')
                episode_final = True  # 次の試行を描画を行う最終試行とする

In [80]:
# main クラス
cartpole_env = Environment()
cartpole_env.run()


Sequential(
  (fc1): Linear(in_features=4, out_features=32, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=32, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=2, bias=True)
)
0 Episode: Finished after 8 steps：10試行の平均step数 = 0.8
1 Episode: Finished after 13 steps：10試行の平均step数 = 2.1
2 Episode: Finished after 10 steps：10試行の平均step数 = 3.1
3 Episode: Finished after 10 steps：10試行の平均step数 = 4.1
4 Episode: Finished after 10 steps：10試行の平均step数 = 5.1
5 Episode: Finished after 9 steps：10試行の平均step数 = 6.0
6 Episode: Finished after 9 steps：10試行の平均step数 = 6.9
7 Episode: Finished after 9 steps：10試行の平均step数 = 7.8
8 Episode: Finished after 8 steps：10試行の平均step数 = 8.6
9 Episode: Finished after 12 steps：10試行の平均step数 = 9.8
10 Episode: Finished after 10 steps：10試行の平均step数 = 10.0
11 Episode: Finished after 10 steps：10試行の平均step数 = 9.7
12 Episode: Finished after 10 steps：10試行の平均step数 = 9.7
13 Episode: Finished after 9 steps：10試行の平均step数 = 9.6
14 Episode: Finis

144 Episode: Finished after 200 steps：10試行の平均step数 = 190.5
145 Episode: Finished after 200 steps：10試行の平均step数 = 190.5
146 Episode: Finished after 200 steps：10試行の平均step数 = 190.5
147 Episode: Finished after 200 steps：10試行の平均step数 = 190.5
148 Episode: Finished after 200 steps：10試行の平均step数 = 200.0
10回連続成功


NoSuchDisplayException: Cannot connect to "None"

# classでなくしてみる

## envのinit

In [56]:
import random
import torch
from torch import nn
from torch import optim
import torch.nn.functional as F

BATCH_SIZE = 32
CAPACITY = 10000

In [57]:
my_env = gym.make(ENV)  # 実行する課題を設定

In [ ]:
num_states = my_env.observation_space.shape[0]  # 課題の状態数4を取得
num_actions = my_env.action_space.n  # CartPoleの行動（右に左に押す）の2を取得

### Agent作成

In [58]:
my_agent = Agent(num_states, num_actions)  # 環境内で行動するAgentを生成

Sequential(
  (fc1): Linear(in_features=4, out_features=32, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=32, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=2, bias=True)
)


In [62]:
my_env.observation_space

Box(4,)

In [63]:
my_env.action_space

Discrete(2)

In [34]:
episode_10_list = np.zeros(10)  # 10試行分の立ち続けたstep数を格納し、平均ステップ数を出力に利用
complete_episodes = 0  # 195step以上連続で立ち続けた試行数
episode_final = False  # 最後の試行フラグ
frames = []  # 最後の試行を動画にするために画像を格納する変数


## envのfor loop

In [64]:
episode = 0

In [65]:
observation = my_env.reset()  # 環境の初期化

In [66]:
state = observation  # 観測をそのまま状態sとして使用
state = torch.from_numpy(state).type(
    torch.FloatTensor)  # NumPy変数をPyTorchのテンソルに変換
state = torch.unsqueeze(state, 0)  # size 4をsize 1x4に変換


In [67]:
state

tensor([[-0.0196,  0.0067,  0.0202,  0.0110]])

In [68]:
type(state)

torch.Tensor

In [69]:
#for step in range(MAX_STEPS):  # 1エピソードのループ
step = 0

In [ ]:
if episode_final is True:  # 最終試行ではframesに各時刻の画像を追加していく
    frames.append(self.env.render(mode='rgb_array'))

### agent.get_actionは$\epsilon$-greedy法により決定されたaction(この例の場合、右か左かのゼロイチ）を返す

In [49]:
action = my_agent.get_action(state, episode)  # 行動を求める

In [51]:
type(action)

torch.Tensor

In [50]:
action.item()

0

### actionを与えるとenvがどうなるかを計算してくれる：

In [71]:
# 行動a_tの実行により、s_{t+1}とdoneフラグを求める
# actionから.item()を指定して、中身を取り出す
observation_next, _, done, _ = my_env.step(
    action.item())  # rewardとinfoは使わないので_にする

In [52]:
done

False

### 終了していたら

* episode_10_list の先頭を削除して、末尾に「今回は何ステップ続いたか」を追加
* 195ステップ未満だった場合、報酬-1を付与
* 195ステップ以上だったら報酬＋１を付与

In [ ]:
# 報酬を与える。さらにepisodeの終了評価と、state_nextを設定する
if done:  # ステップ数が200経過するか、一定角度以上傾くとdoneはtrueになる
    state_next = None  # 次の状態はないので、Noneを格納

    # 直近10episodeの立てたstep数リストに追加
    episode_10_list = np.hstack(
        (episode_10_list[1:], step + 1))

    if step < 195:
        reward = torch.FloatTensor(
            [-1.0])  # 途中でこけたら罰則として報酬-1を与える
        complete_episodes = 0  # 連続成功記録をリセット
    else:
        reward = torch.FloatTensor([1.0])  # 立ったまま終了時は報酬1を与える
        complete_episodes = complete_episodes + 1  # 連続記録を更新

In [72]:
if not done:
    reward = torch.FloatTensor([0.0])  # 普段は報酬0
    state_next = observation_next  # 観測をそのまま状態とする
    state_next = torch.from_numpy(state_next).type(
        torch.FloatTensor)  # numpy変数をPyTorchのテンソルに変換
    state_next = torch.unsqueeze(state_next, 0)  # size 4をsize 1x4に変換

### エージェントが（状態、アクション、次のアクション、報酬）を記憶

In [73]:
# メモリに経験を追加
my_agent.memorize(state, action, state_next, reward)

### Experience ReplayでQ関数を更新する

In [76]:
my_agent.update_q_function()

In [77]:
# 観測の更新
state = state_next

In [ ]:
# 終了時の処理
if done:
    print('%d Episode: Finished after %d steps：10試行の平均step数 = %.1lf' % (
        episode, step + 1, episode_10_list.mean()))
    break

## brain

### サンプルがたまった学習済みのbrainを拝借

In [83]:
my_brain = cartpole_env.agent.brain

### mini batch取得

In [84]:
transitions = my_brain.memory.sample(BATCH_SIZE)

In [90]:
len(transitions)

32

In [91]:
transitions[0:3]

[Transition(state=tensor([[-0.0474, -0.1739,  0.0059,  0.2582]]), action=tensor([[1]]), next_state=tensor([[-0.0508,  0.0211,  0.0110, -0.0326]]), reward=tensor([0.])),
 Transition(state=tensor([[ 0.0222, -0.1858, -0.0523,  0.0235]]), action=tensor([[1]]), next_state=tensor([[ 0.0184,  0.0100, -0.0519, -0.2852]]), reward=tensor([0.])),
 Transition(state=tensor([[-0.2261, -0.5464, -0.0204,  0.2635]]), action=tensor([[1]]), next_state=tensor([[-0.2370, -0.3510, -0.0151, -0.0355]]), reward=tensor([0.]))]

### mini batchをtorchが食える形式に変形

In [ ]:
# 2.2 各変数をミニバッチに対応する形に変形
# transitionsは1stepごとの(state, action, state_next, reward)が、BATCH_SIZE分格納されている
# つまり、(state, action, state_next, reward)×BATCH_SIZE
# これをミニバッチにしたい。つまり
# (state×BATCH_SIZE, action×BATCH_SIZE, state_next×BATCH_SIZE, reward×BATCH_SIZE)にする
batch = Transition(*zip(*transitions))

In [94]:
len(batch)

4

In [96]:
batch[0][0:3]

(tensor([[-0.0474, -0.1739,  0.0059,  0.2582]]),
 tensor([[ 0.0222, -0.1858, -0.0523,  0.0235]]),
 tensor([[-0.2261, -0.5464, -0.0204,  0.2635]]))

In [99]:
batch.state[0:3]

(tensor([[-0.0474, -0.1739,  0.0059,  0.2582]]),
 tensor([[ 0.0222, -0.1858, -0.0523,  0.0235]]),
 tensor([[-0.2261, -0.5464, -0.0204,  0.2635]]))

In [97]:
# 2.3 各変数の要素をミニバッチに対応する形に変形し、ネットワークで扱えるようVariableにする
# 例えばstateの場合、[torch.FloatTensor of size 1x4]がBATCH_SIZE分並んでいるのですが、
# それを torch.FloatTensor of size BATCH_SIZEx4 に変換します
# 状態、行動、報酬、non_finalの状態のミニバッチのVariableを作成
# catはConcatenates（結合）のことです。
state_batch = torch.cat(batch.state)
action_batch = torch.cat(batch.action)
reward_batch = torch.cat(batch.reward)
non_final_next_states = torch.cat([s for s in batch.next_state
                                   if s is not None])

In [101]:
state_batch.shape


torch.Size([32, 4])

### 推論モードへ切り替え

In [102]:
# -----------------------------------------
# 3. 教師信号となるQ(s_t, a_t)値を求める
# -----------------------------------------
# 3.1 ネットワークを推論モードに切り替える
my_brain.model.eval()

Sequential(
  (fc1): Linear(in_features=4, out_features=32, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=32, out_features=32, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=32, out_features=2, bias=True)
)

###  ネットワークが出力したQ(s_t, a_t)を求める

In [104]:
# self.model(state_batch)は、右左の両方のQ値を出力しており
# [torch.FloatTensor of size BATCH_SIZEx2]になっている。
# ここから実行したアクションa_tに対応するQ値を求めるため、action_batchで行った行動a_tが右か左かのindexを求め
# それに対応するQ値をgatherでひっぱり出す。
state_action_values = my_brain.model(state_batch).gather(1, action_batch)

In [106]:
state_action_values.shape

torch.Size([32, 1])

In [105]:
state_action_values

tensor([[ 0.0811],
        [-0.0088],
        [-0.1474],
        [ 0.1030],
        [ 0.1201],
        [-0.2402],
        [-0.0771],
        [ 0.0712],
        [-1.0143],
        [-0.3686],
        [ 0.0666],
        [-0.0042],
        [-0.1668],
        [ 0.0476],
        [ 0.0465],
        [ 0.1613],
        [-0.2929],
        [-0.6168],
        [ 0.1461],
        [ 0.0671],
        [-0.2055],
        [ 0.0821],
        [-0.2846],
        [-0.7647],
        [ 0.0921],
        [ 0.1298],
        [-0.5426],
        [-0.3158],
        [-0.2658],
        [-0.0334],
        [ 0.1501],
        [ 0.0792]], grad_fn=<GatherBackward>)

### cartpoleがdoneになっておらず、next_stateがあるかをチェックするインデックスマスクを作成

In [107]:
non_final_mask = torch.ByteTensor(tuple(map(lambda s: s is not None,
                                            batch.next_state)))

In [134]:
non_final_mask

tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 1], dtype=torch.uint8)

In [114]:
# まずは全部0にしておく
next_state_values = torch.zeros(BATCH_SIZE)

#### doneでないnext state:

In [125]:
non_final_next_states[0:10]

tensor([[-0.0508,  0.0211,  0.0110, -0.0326],
        [ 0.0184,  0.0100, -0.0519, -0.2852],
        [-0.2370, -0.3510, -0.0151, -0.0355],
        [-0.0136,  0.2277, -0.0011, -0.2597],
        [ 0.0445,  0.1779,  0.0080, -0.1628],
        [-0.3392, -0.5192, -0.0106,  0.0641],
        [-0.5775,  0.2264,  0.1267, -0.1718],
        [-0.0049, -0.0482,  0.0122, -0.0173],
        [-0.0262, -0.3208, -0.1448, -0.2931],
        [ 0.0143, -0.1475, -0.0332,  0.1395]])

#### next statenにおける行動価値関数

In [127]:
my_brain.model(non_final_next_states)[0:10]

tensor([[ 0.0671,  0.0825],
        [-0.0150, -0.0931],
        [-0.1746, -0.1917],
        [ 0.1026,  0.0694],
        [ 0.1074,  0.0962],
        [-0.2518, -0.2642],
        [-0.0532, -0.0609],
        [ 0.0588,  0.0784],
        [-0.3069, -0.4145],
        [ 0.0250,  0.0737]], grad_fn=<SliceBackward>)

#### next stateにおける行動価値関数の最大値

In [129]:
my_brain.model(non_final_next_states).max(1)

(tensor([ 0.0825, -0.0150, -0.1746,  0.1026,  0.1074, -0.2518, -0.0532,  0.0784,
         -0.3069,  0.0737,  0.0038, -0.1840,  0.0346,  0.0513,  0.1618, -0.3278,
         -0.5720,  0.1650,  0.0815, -0.1134,  0.0891, -0.2461, -0.7838,  0.0817,
         -0.3577, -0.2595, -0.0408,  0.1413,  0.0772], grad_fn=<MaxBackward0>),
 tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
         1, 1, 0, 0, 0]))

このように最大値と最大値を返すインデックスが返る    

In [131]:
type(my_brain.model(non_final_next_states).max(1))

tuple

In [132]:
# 次の状態があるindexの最大Q値を求める
# 出力にアクセスし、max(1)で列方向の最大値の[値、index]を求めます
# そしてそのQ値（index=0）を出力します
# detachでその値を取り出します
next_state_values[non_final_mask] = my_brain.model(
    non_final_next_states).max(1)[0].detach()

In [133]:
next_state_values

tensor([ 0.0825, -0.0150, -0.1746,  0.1026,  0.1074, -0.2518, -0.0532,  0.0784,
         0.0000, -0.3069,  0.0737,  0.0038, -0.1840,  0.0346,  0.0513,  0.1618,
        -0.3278, -0.5720,  0.1650,  0.0815, -0.1134,  0.0891, -0.2461, -0.7838,
         0.0817,  0.0000,  0.0000, -0.3577, -0.2595, -0.0408,  0.1413,  0.0772])

$\uparrow$ next stateがdoneでないsampleに関してはnext stateにおける行動価値関数のmax(最適行動をとったときの値)が、next stateがdoneならゼロが格納されている

In [117]:
%%bash
git commit -a -m "checkpoint"

[master 679651f] checkpoint
 1 file changed, 159 insertions(+), 6 deletions(-)


In [ ]:
# 3.4 教師となるQ(s_t, a_t)値を、Q学習の式から求める
expected_state_action_values = reward_batch + GAMMA * next_state_values

# -----------------------------------------
# 4. 結合パラメータの更新
# -----------------------------------------
# 4.1 ネットワークを訓練モードに切り替える
self.model.train()

# 4.2 損失関数を計算する（smooth_l1_lossはHuberloss）
# expected_state_action_valuesは
# sizeが[minbatch]になっているので、unsqueezeで[minibatch x 1]へ
loss = F.smooth_l1_loss(state_action_values,
                        expected_state_action_values.unsqueeze(1))

# 4.3 結合パラメータを更新する
self.optimizer.zero_grad()  # 勾配をリセット
loss.backward()  # バックプロパゲーションを計算
self.optimizer.step()  # 結合パラメータを更新

# sandbox

In [26]:
num_states


4

### 経験を記憶するメモリオブジェクトを生成

In [33]:
my_memory = ReplayMemory(CAPACITY)

In [34]:
my_memory

### ニューラルネットワークを構築

In [31]:
my_model = nn.Sequential()
my_model.add_module('fc1', nn.Linear(num_states, 32))
my_model.add_module('relu1', nn.ReLU())
my_model.add_module('fc2', nn.Linear(32, 32))
my_model.add_module('relu2', nn.ReLU())
my_model.add_module('fc3', nn.Linear(32, num_actions))

### 最適化手法の設定

In [32]:
my_optimizer = optim.Adam(my_model.parameters(), lr=0.0001)

### replay